package entitygraph
package entitygraph_test

import (
	"testing"








































































































































}	}		t.Errorf("Inverse: got %q", rd.Inverse)	if rd.Inverse != "belongs_to_agency" {	}		t.Errorf("ToType: got %q", rd.ToType)	if rd.ToType != "AgencySnapshot" {	}		t.Errorf("Name: got %q", rd.Name)	if rd.Name != "has_snapshot" {	}		Inverse:  "belongs_to_agency",		Required: false,		ToMany:   true,		ToType:   "AgencySnapshot",		Label:    "Snapshots",		Name:     "has_snapshot",	rd := types.RelationshipDefinition{func TestRelationshipDefinition_AllFields(t *testing.T) {// ── RelationshipDefinition field values ──────────────────────────────────────}	}		t.Fatal("expected error for type with no relationships, got nil")	if err == nil {	_, err := entitygraph.FindRelationshipDef(td, "has_goal")	td := types.TypeDefinition{Name: "Bare", Relationships: nil}func TestFindRelationshipDef_TypeWithNoRelationships_ReturnsError(t *testing.T) {}	}		t.Fatal("expected error, got nil")	if err == nil {	_, err := entitygraph.FindRelationshipDef(td, "nonexistent_label")	td, _ := entitygraph.FindTypeDef(schema, "Agency")	schema := testSchema()func TestFindRelationshipDef_UnknownLabel_ReturnsError(t *testing.T) {}	}		t.Error("expected ToMany = false for belongs_to_agency")	if rd.ToMany {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	rd, err := entitygraph.FindRelationshipDef(td, "belongs_to_agency")	td, _ := entitygraph.FindTypeDef(schema, "Goal")	schema := testSchema()func TestFindRelationshipDef_FunctionalLabel_ToManyFalse(t *testing.T) {}	}		t.Error("expected ToMany = true for has_goal")	if !rd.ToMany {	}		t.Errorf("got ToType %q, want %q", rd.ToType, "Goal")	if rd.ToType != "Goal" {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	rd, err := entitygraph.FindRelationshipDef(td, "has_goal")	td, _ := entitygraph.FindTypeDef(schema, "Agency")	schema := testSchema()func TestFindRelationshipDef_ExistingLabel_ReturnsDef(t *testing.T) {// ── FindRelationshipDef ──────────────────────────────────────────────────────}	}		t.Fatal("expected error, got nil")	if err == nil {	_, err := entitygraph.FindTypeDef(types.Schema{ID: "empty"}, "Agency")func TestFindTypeDef_EmptySchema_ReturnsError(t *testing.T) {}	}		t.Fatal("expected error, got nil")	if err == nil {	_, err := entitygraph.FindTypeDef(schema, "NonExistent")	schema := testSchema()func TestFindTypeDef_UnknownType_ReturnsError(t *testing.T) {}	}		t.Errorf("got name %q, want %q", td.Name, "Agency")	if td.Name != "Agency" {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	td, err := entitygraph.FindTypeDef(schema, "Agency")	schema := testSchema()func TestFindTypeDef_ExistingType_ReturnsDef(t *testing.T) {// ── FindTypeDef ──────────────────────────────────────────────────────────────}	}		},			},				},					{Name: "belongs_to_agency", Label: "Agency", ToType: "Agency", ToMany: false},				Relationships: []types.RelationshipDefinition{				},					{Name: "title", Type: types.PropertyTypeString, Required: true},				Properties: []types.PropertyDefinition{				DisplayName: "Goal",				Name:        "Goal",			{			},				},					{Name: "has_workflow", Label: "Workflows", ToType: "Workflow", ToMany: true},					{Name: "has_goal",    Label: "Goals",    ToType: "Goal",    ToMany: true},				Relationships: []types.RelationshipDefinition{				},					{Name: "name", Type: types.PropertyTypeString, Required: true},				Properties: []types.PropertyDefinition{				DisplayName: "Agency",				Name:        "Agency",			{		Types: []types.TypeDefinition{		Tag:     "v1",		Version: 1,		ID:      "test-schema-v1",	return types.Schema{func testSchema() types.Schema {// testSchema builds a minimal Schema for use in lookup tests.)	"github.com/aosanya/CodeValdSharedLib/types"	"github.com/aosanya/CodeValdSharedLib/entitygraph"